export default categoryList = [
    "All",
    "Alcohol",
    "Burgers",
    "Breakfast/Brunch",
    "BBQ",
    "Coffee/Tea",
    "Bakery",
    "Convenience Store",
    "Chicken",
    "Cajun/Creole",
    "Vegetarian",
    "Sandwhiches/Subs",
    "Desserts",
    "Healthy",
    "Wings",
    "Indian",
    "Gluten Friendly",
    "Pizza",
    "Fusion",
    "Pub Food",
    "Smoothies",
    "Donair",
    "Vegan",
    "Chinese",
    "Diner",
    "Halal",
    "Pitas",
    "Vietnamese",
    "Japanese",
    "Fish & Chips",
    "Ice Cream",
    "Sushi",
    "Middle Eastern",
    "Italian",
    "Steakhouse",
    "Thai",
    "Mexican",
    "Tacos",
    "Korean",
    "Greek",
]